<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.grocery</groupId>
    <artifactId>online-grocery-store</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Online-grocery-store</name>
    <description>Online-grocery-store</description>
    <packaging>pom</packaging>

    <modules>
        <module>backend/common-library</module>
        <module>backend/product-catalog-service</module>
        <module>backend/inventory-service</module>
        <module>backend/order-service</module>
        <module>backend/eureka-server</module>
        <module>backend/config-server</module>
    </modules>

    <properties>
        <common-lib.version>1.0.0</common-lib.version>
        <spring-boot.version>3.4.6</spring-boot.version>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <spring-cloud.version>2024.0.2</spring-cloud.version>
        <spring-doc.version>2.8.14</spring-doc.version>
        <postgres.version>42.7.7</postgres.version>
        <flyway.version>11.10.1</flyway.version>
        <resilience4j.version>2.3.0</resilience4j.version>
        <lombok.version>1.18.42</lombok.version>
        <jib.version>3.5.1</jib.version>
        <image.tag>a3</image.tag>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.grocery</groupId>
                <artifactId>common-library</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
