server:
  port: 8083

spring:
  application:
    name: product-catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"